# fly.toml app configuration file generated for vitronmax-frontend on 2025-05-26T21:48:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vitronmax-frontend'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/usr/share/nginx/html'
  url_prefix = '/'
