app = "vitronmax"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "INFO"
  ENV = "production"
  STORAGE_BUCKET_NAME = "vitronmax-storage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

[metrics]
  port = 8080
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
