// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqpcphskuiqwiavqrxos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxcGNwaHNrdWlxd2lhdnFyeG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTU1ODUsImV4cCI6MjA2MzIzMTU4NX0.Y4hd_D_ItzcHXGJzok9X4MTEtgy96Makawx7l3_uIAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);